config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :recipes, only: [:index, :new, :create, :show]
  resources :recipes

  resources :recipes do
    resources :likes, only: [:create, :destroy]
  end

  get 'users/new'
  get 'users/create'
  get 'users/:id', to: 'users#show', as: 'user'


  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'recipes', to: 'pages#recipes'
  get 'add_recipe', to: 'pages#addrecipe'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  # Add more routes as needed
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one_attached :image
  has_many :likes
  has_many :liked_by_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes
  has_many :liked_recipes, through: :likes, source: :recipe
  has_many :recipes
  has_secure_password
  # Rest of your User model code
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :logged_in?
  before_action :set_recipes
  def set_recipes
    @recipes_new = Recipe.last(3).reverse
  end

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private

  def logged_in?
    session[:user_id].present?
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  def create
    @recipe = Recipe.find(params[:recipe_id])
    current_user.likes.create(recipe: @recipe)

  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    current_user.likes.find_by(recipe: @recipe).destroy

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def profile
  end

  def register
  end

  def login
  end

  def add_recipe
  end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully!'
    else
      render :new
    end
  end


  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :html_details, :image, :text, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]
    user = User.find_by(email: email)

    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully!'
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вихід виконано успішно!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    existing_user = User.find_by(email: user_params[:email])
    if existing_user
      flash.now[:alert] = 'User with this email already exists.'
      render :new
    else
      @user = User.new(user_params)
      if valid_email?(@user.email) && @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Registration successful!'
      else
        flash.now[:alert] = 'Invalid email format. Please enter a valid email address.'
        render :new
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @liked_recipes = @user.likes.map(&:recipe)
    @recipes_added = @user.recipes
  end


  def liked_recipes
    @user = User.find(params[:id])
    @liked_recipes = @user.liked_recipes
  end



  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


  def valid_email?(email)
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    email.match?(email_regex)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Culinary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <!-- Add your Bootstrap menu here -->

  <nav class="navbar navbar-expand-lg sticky-top navbar navbar-dark bg-dark menu >
    <div class="container menu">
       <img src="/assets/logo.png" alt="Image 2" style="width: 50px">
       <%= link_to 'KURISU MEAL', root_path, class: 'navbar-brand brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarNav">
        <ul class="navbar-nav ">
          <li class="nav-item ">
            <%= link_to 'Рецепти', recipes_path, class: 'nav-link menu' %>
          </li>
            <%= link_to 'Про нас', about_path, class: 'nav-link menu' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Контакти', contact_path, class: 'nav-link menu' %>
          </li>

          <% if logged_in? %>
              <div class="dropdown nav-item">
                <div class="dropdown">
                  <%= link_to 'Профіль', user_path(current_user), class: 'btn btn-secondary dropdown-toggle menu marginl' %>
                  <div class="dropdown-options dropdown-menu">
                    <%= button_to 'Вийти', logout_path, method: :delete, class: 'dropdown-item menu' %>
                    <%= link_to 'Додати рецепт', new_recipe_path, class: 'dropdown-item menu' %>
                  </div>
                </div>
              </div>
          <% else %>
              <div class="dropdown nav-item">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle menu marginl">Профіль</button>
                  <div class="dropdown-options dropdown-menu">
                    <%= link_to 'Зареєструватися', signup_path, class: 'dropdown-item menu' %>
                    <%= link_to 'Увійти', login_path, class: 'dropdown-item menu' %>
                  </div>
                </div>
              </div>
          <% end %>

          <div>

          </div>
          <!-- Add more menu items as needed -->
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>


  <footer style="margin-top: 50px" class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-a692"><div class="u-clearfix u-sheet u-sheet-1">
    <p class="u-small-text u-text u-text-variant u-text-1">KURISU MEAL</p>
  </div></footer>
  <section class="u-backlink u-clearfix u-grey-80">
    <span>Вебсайт створений для ваших кулінарних смаків</span>
  </section>

  <!-- Include Bootstrap JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Про нас - KURISU MEAL</title>
  <style>
    .container {
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      align-items: center;
      gap: 20px;
    }

    .image-card {
      width: 300px;
      text-align: center;
    }

    .image-card img {
      width: 100%;
      height: auto;
    }
  </style>
</head>
<body>
<h1>Про нас</h1>
<div class="container">
  <div class="image-card">
    <img src="/assets/about2.jpg" alt="Image 1">
  </div>
  <div class="image-card">
    <img src="/assets/kurisu.png" alt="Image 2">
  </div>
  <div class="image-card">
    <img src="/assets/about3.png" alt="Image 3">
  </div>
  <h1>KURISU MEAL</h1>
  <!-- Додайте більше картинок та описів за необхідністю -->
</div>
<h4>Опис про веб-сайт KURISU MEAL</h4>
<img src="/assets/about1.png" alt="Image 4">
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Кулінарні рецепти</title>

  <style>
    /* Custom Styles */
    .recipe-block {
      margin-top: 20px;
    }
    body, html {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    .caption-content {
      position: absolute;
      top: 40%;
      left: 50%;
      transform: translate(-50%, -50%);
      text-align: center;
      color: white;
      background-color: rgba(0, 0, 0, 0.5);
      padding: 20px;
    }

    #carouselExampleIndicators {
      width: 100vw; /* Займає 100% ширини вікна перегляду */
      max-width: 100%; /* Не перевищує ширину вікна перегляду */
      margin: 0; /* Відміняємо зовнішні відступи */
      padding: 0; /* Відміняємо внутрішні відступи */
    }

    .carousel-item img {
      width: 100%; /* Займає 100% ширини слайдера */
    }




    @keyframes scrollBackground {
      0% {
        background-position: 0 0;
      }
      100% {
        background-position: -100% 0;
      }
    }
  </style>
</head>
<body>
<div id="carouselExampleIndicators" class="carousel slide" style="height: 600px; margin-top: 50px"; data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" style="height: 600px; ">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/assets/food1.jpg" >
      <div class="caption-content" >
        <div>
        <h5 >KURISU MEAL</h5>
        <p>Від смачних ласощів та ідей для вечері на вихідні до здорових закусок та страв з однієї каструлі - у нас є все, чого ви прагнете.</p>
          <%= link_to 'Детальніше', recipes_path, class: 'btn btn-warning margins' %>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/food2.jpg">
      <div class="caption-content">
        <h5>Покращуйте своє харчування</h5>
        <p>Зробіть ранкові сніданки незабутніми завдяки смачним основним стравам, гарнірам та солодощам</p>
        <%= link_to 'Детальніше', recipes_path, class: 'btn btn-warning margins' %>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/food3.jpg">
      <div class="caption-content">
        <h5>Про нас</h5>
        <p>Використовуйте наш сервіс для покращення вашого життя</p>
        <%= link_to 'Детальніше', about_path, class: 'btn btn-warning margins' %>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Попередній</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Наступний</span>
  </a>
</div>

<div class="fullscreen-section">
  <!-- Зміст блоку -->
  <div class="container">
  </div>
</div>



<div class="recipe-block" style="margin-top: 350px">
  <h2>Останні рецепти</h2>
  <div class="row">
    <% @recipes_new.reverse_each do |recipe| %>
        <div class="col-md-4">
          <div class="card mb-4">
            <%= image_tag recipe.image if recipe.image.attached? %>
            <div class="card-body">
              <h5 class="card-title"><%= recipe.title %></h5>
              <p class="card-text"><%= recipe.text %></p>
              <div style="text-align: center">
                <%= link_to "Дивитися повністю",  recipe_path(recipe), class: "btn btn-warning" %>
                <% if logged_in? %>
                    <%= button_to  "Не подобається", recipe_like_path(recipe, current_user), method: :delete, class: "btn btn-warning"%>
                    <%= button_to  "Подобається", recipe_likes_path(recipe), method: :post, class: "btn btn-warning" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/recipes/index.html.erb
<h1>Рецепти</h1>

<div class="row">
  <% @recipes.reverse_each do |recipe| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <%= image_tag recipe.image if recipe.image.attached? %>
          <div class="card-body">
            <h5 class="card-title"><%= recipe.title %></h5>
            <p class="card-text"><%= recipe.text %></p>
            <div style="text-align: center">
            <%= link_to "Дивитися повністю",  recipe_path(recipe), class: "btn btn-warning" %>
            <% if logged_in? %>
                <%= button_to  "Не подобається", recipe_like_path(recipe, current_user), method: :delete, class: "btn btn-warning"%>
                <%= button_to  "Подобається", recipe_likes_path(recipe), method: :post, class: "btn btn-warning" %>
            <% end %>
              </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h2>Реєстрація</h2>

<% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
<% end %>

<%= form_with(model: @user, url: signup_path, class: 'signup-form') do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: 'form-control', required: true %>
    </div>

    <%= form.submit 'Зареєструватися', class: 'btn btn-dark' %>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html style="font-size: 16px;" lang="ua"><head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  <meta name="keywords" content="Профіль">
  <meta name="description" content="">
  <title>Головна</title>
  <link rel="stylesheet" href="nicepage.css" media="screen">
  <link rel="stylesheet" href="profile.css" media="screen">
  <script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>
  <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
  <meta name="generator" content="Nicepage 5.10.3, nicepage.com">

  <style>
    /* Menu Styles */
    .menu_pr {
      background-color: #f2f2f2;
      padding: 10px;
      margin-top: 30px;
      text-align: center;
    }

    .menu_pr ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
    }

    .menu_pr li {
      display: inline-block;
      margin-right: 10px;

    }

    .menu_pr a {
      color: #333;
      text-decoration: none;
      padding: 5px;
    }

    .menu_pr a:hover {
      background-color: #ccc;
    }
  </style>


  <meta name="theme-color" content="#478ac9">
  <meta property="og:title" content="Головна">
  <meta property="og:type" content="website">
  <meta data-intl-tel-input-cdn-path="intlTelInput/"></head>
<body class="u-body u-xl-mode" data-lang="ua">
<section class="u-align-center u-clearfix u-white u-section-1" id="carousel_def0">
  <div class="u-clearfix u-sheet u-valign-middle-lg u-valign-middle-md u-valign-middle-sm u-valign-middle-xs u-sheet-1">
    <h1 class="u-custom-font u-font-raleway u-text u-text-default u-text-palette-1-base u-text-1">Профіль</h1>
    <div class="u-align-left u-container-style u-expanded-width-md u-expanded-width-sm u-expanded-width-xs u-group u-palette-1-base u-radius-20 u-shape-round u-group-1">
      <div class="u-container-layout u-valign-top u-container-layout-1">
        <h6 class="u-custom-font u-font-open-sans u-text u-text-default u-text-2">ПІБ</h6>
        <p class="u-custom-font u-text u-text-3">Fred Morrison</p>
        <h6 class="u-custom-font u-font-open-sans u-text u-text-default u-text-4">Email</h6>
        <a href="https://nicepage.one" class="u-border-1 u-border-active-palette-1-light-2 u-border-hover-palette-1-light-2 u-border-no-left u-border-no-right u-border-no-top u-btn u-button-style u-none u-text-active-palette-1-light-2 u-text-body-alt-color u-text-hover-palette-1-light-2 u-btn-1">designer@example.com</a>
        <h6 class="u-custom-font u-font-open-sans u-text u-text-default u-text-7">Соц. мережі</h6>
        <div class="u-social-icons u-spacing-10 u-social-icons-1">
          <a class="u-social-url" title="facebook" target="_blank" href="https://facebook.com/name"><span class="u-icon u-icon-circle u-social-facebook u-social-icon u-text-white"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-4113"></use></svg><svg class="u-svg-content" viewBox="0 0 112 112" x="0" y="0" id="svg-4113"><path fill="currentColor" d="M75.5,28.8H65.4c-1.5,0-4,0.9-4,4.3v9.4h13.9l-1.5,15.8H61.4v45.1H42.8V58.3h-8.8V42.4h8.8V32.2
c0-7.4,3.4-18.8,18.8-18.8h13.8v15.4H75.5z"></path></svg></span>
          </a>
          <a class="u-social-url" title="twitter" target="_blank" href="https://twitter.com/name"><span class="u-icon u-icon-circle u-social-icon u-social-twitter u-text-white"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-3c2e"></use></svg><svg class="u-svg-content" viewBox="0 0 112 112" x="0" y="0" id="svg-3c2e"><path fill="currentColor" d="M92.2,38.2c0,0.8,0,1.6,0,2.3c0,24.3-18.6,52.4-52.6,52.4c-10.6,0.1-20.2-2.9-28.5-8.2
	c1.4,0.2,2.9,0.2,4.4,0.2c8.7,0,16.7-2.9,23-7.9c-8.1-0.2-14.9-5.5-17.3-12.8c1.1,0.2,2.4,0.2,3.4,0.2c1.6,0,3.3-0.2,4.8-0.7
	c-8.4-1.6-14.9-9.2-14.9-18c0-0.2,0-0.2,0-0.2c2.5,1.4,5.4,2.2,8.4,2.3c-5-3.3-8.3-8.9-8.3-15.4c0-3.4,1-6.5,2.5-9.2
	c9.1,11.1,22.7,18.5,38,19.2c-0.2-1.4-0.4-2.8-0.4-4.3c0.1-10,8.3-18.2,18.5-18.2c5.4,0,10.1,2.2,13.5,5.7c4.3-0.8,8.1-2.3,11.7-4.5
	c-1.4,4.3-4.3,7.9-8.1,10.1c3.7-0.4,7.3-1.4,10.6-2.9C98.9,32.3,95.7,35.5,92.2,38.2z"></path></svg></span>
          </a>
          <a class="u-social-url" title="instagram" target="_blank" href="https://instagram.com/name"><span class="u-icon u-icon-circle u-social-icon u-social-instagram u-text-white"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-a922"></use></svg><svg class="u-svg-content" viewBox="0 0 112 112" x="0" y="0" id="svg-a922"><path fill="currentColor" d="M55.9,32.9c-12.8,0-23.2,10.4-23.2,23.2s10.4,23.2,23.2,23.2s23.2-10.4,23.2-23.2S68.7,32.9,55.9,32.9z
	 M55.9,69.4c-7.4,0-13.3-6-13.3-13.3c-0.1-7.4,6-13.3,13.3-13.3s13.3,6,13.3,13.3C69.3,63.5,63.3,69.4,55.9,69.4z"></path><path fill="#FFFFFF" d="M79.7,26.8c-3,0-5.4,2.5-5.4,5.4s2.5,5.4,5.4,5.4c3,0,5.4-2.5,5.4-5.4S82.7,26.8,79.7,26.8z"></path><path fill="currentColor" d="M78.2,11H33.5C21,11,10.8,21.3,10.8,33.7v44.7c0,12.6,10.2,22.8,22.7,22.8h44.7c12.6,0,22.7-10.2,22.7-22.7
	V33.7C100.8,21.1,90.6,11,78.2,11z M91,78.4c0,7.1-5.8,12.8-12.8,12.8H33.5c-7.1,0-12.8-5.8-12.8-12.8V33.7
	c0-7.1,5.8-12.8,12.8-12.8h44.7c7.1,0,12.8,5.8,12.8,12.8V78.4z"></path></svg></span>
          </a>
          <a class="u-social-url" target="_blank" data-type="Custom" title="Custom" href=""><span class="u-icon u-icon-circle u-social-custom u-social-icon u-text-white u-icon-4"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 512 512" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-a7cd"></use></svg><svg class="u-svg-content" viewBox="0 0 512 512" x="0px" y="0px" id="svg-a7cd" style="enable-background:new 0 0 512 512;"><g><g><path d="M490.24,113.92c-13.888-24.704-28.96-29.248-59.648-30.976C399.936,80.864,322.848,80,256.064,80    c-66.912,0-144.032,0.864-174.656,2.912c-30.624,1.76-45.728,6.272-59.744,31.008C7.36,138.592,0,181.088,0,255.904    C0,255.968,0,256,0,256c0,0.064,0,0.096,0,0.096v0.064c0,74.496,7.36,117.312,21.664,141.728    c14.016,24.704,29.088,29.184,59.712,31.264C112.032,430.944,189.152,432,256.064,432c66.784,0,143.872-1.056,174.56-2.816    c30.688-2.08,45.76-6.56,59.648-31.264C504.704,373.504,512,330.688,512,256.192c0,0,0-0.096,0-0.16c0,0,0-0.064,0-0.096    C512,181.088,504.704,138.592,490.24,113.92z M192,352V160l160,96L192,352z"></path>
</g>
</g></svg></span>
          </a>
        </div>
        <div class="buttonex">
          <%= button_to 'Редагувати профіль', logout_path, method: :delete, class: 'btn btn-warning margins' %>
        </div>
        <div class="buttonex">
          <%= button_to 'Вийти з профілю', logout_path, method: :delete, class: 'btn btn-warning margins' %>
        </div>
      </div>
    </div>
    <img class="u-expanded-width-md u-expanded-width-sm u-expanded-width-xs u-image u-image-round u-radius-20 u-image-1" alt="" data-image-width="997" data-image-height="700" src="/assets/profile.jpg">
  </div>
</section>
    <section class="u-align-center u-clearfix u-section-2" id="sec-4b50">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h1 class="u-text u-text-default u-text-1">Вподобані рецепти</h1>
      </div>
    </section>
    <div class="row">
            <% @liked_recipes.reverse_each do |recipe| %>
                <div class="col-md-4">
                  <div class="card mb-4 ">
                    <%= image_tag recipe.image if recipe.image.attached? %>
                    <div class="card-body">
                      <h5 class="card-title margint"><%= recipe.title %></h5>
                      <p class="card-text"><%= recipe.text %></p>
                      <div style="text-align: center !important; ">
                      <%= link_to "Дивитися повністю",  recipe_path(recipe), class: "btn btn-warning margint"%>
                      <%= button_to  "Не подобається", recipe_like_path(recipe, current_user), method: :delete, class: "btn btn-warning margint" %>
                    </div>
                      </div>
                  </div>
                </div>
            <% end %>
      </div>

    <section class="u-align-center u-clearfix u-section-2" id="sec-4b50">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h1 class="u-text u-text-default u-text-1">Додані рецепти</h1>
      </div>
    </section>
    <div class="row">
      <% @recipes_added.reverse_each do |recipe| %>
          <div class="col-md-4">
            <div class="card mb-4" style="text-align: center">
              <%= image_tag recipe.image if recipe.image.attached? %>
              <div class="card-body">
                <h5 class="card-title"><%= recipe.title %></h5>
                <p class="card-text"><%= recipe.text %></p>
                <%= link_to "Дивитися повністю",  recipe_path(recipe), class: "btn btn-warning margint"%>
                <%= button_to  "Не подобається", recipe_like_path(recipe, current_user), method: :delete, class: "btn btn-warning margint" %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
    <section class="u-clearfix u-section-4" id="sec-16c0">
      <div class="u-clearfix u-sheet u-sheet-1"></div>
    </section>

</body></html>